---
- hosts: EXAM  
  become: yes
  become_user: root 
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: test connection
    ping:
  - name: install Pip     
    apt: name=python3-pip state=present
  - name: install docker-py
    pip: name=docker-py

  - name: build the image
    docker_image: 
      name: website
      tag: v1
      path: /DevOps/Examen/Jenkins/workspace/ExamPip/Project_API2/ClientApp
      state: build
  - name: build image with cmd
    command: docker run -d --name websiteonly -p80:80 website:v1
  #Dit geeft een error dat er parameter missen
  # - name: Running the container
  #   docker_container:
  #     image: website:latest
  #     path: /DevOps/Examen/Jenkins/workspace/ExamPip/Project_API2/ClientApp
  #     state: running
  - name: run docker image
    command: docker run -d --name websiteOnly -p 80:80 website