---
- hosts: EXAM  
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: test connection
    ping:

  - name: install Pip
    become: yes
    become_user: root  
    apt:  name=python-pip state=present

  - name: install docker-py
    become: yes
    become_user: root 
    pip: name=docker-py

  - name: build the image
    docker_image: 
      name: websiteExam
      path: /DevOps/Examen/Jenkins/workspace/ExamPip/Project_API2/ClientApp
      state: build

  # - name: install epel-release
  #   yum:
  #     name: epel-release
  #     state: latest