---
- hosts: EXAM
  remote_user: root
  tasks:
  - name: test connection
    ping:
  - name: move to Dir
    command: pwd
    command: cd /DevOps/Examen/Jenkins/workspace/ 
    command: pwd

  # - name: install epel-release
  #   yum:
  #     name: epel-release
  #     state: latest